const LIGUE1_OFFICIAL_NAMES: Record<string, string> = {
  angers: 'Angers SCO',
  auxerre: 'AJ Auxerre',
  brest: 'Stade Brestois 29',
  lehavre: 'Le Havre AC',
  rclens: 'RC Lens',
  lille: 'LOSC Lille',
  fclorient: 'FC Lorient',
  lorient: 'FC Lorient',
  lyon: 'Olympique Lyonnais',
  marseille: 'Olympique de Marseille',
  metz: 'FC Metz',
  asmonacofc: 'AS Monaco FC',
  asmonaco: 'AS Monaco FC',
  nantes: 'FC Nantes',
  nice: 'OGC Nice',
  parisfc: 'Paris FC',
  parissaintgermain: 'Paris Saint-Germain',
  rennes: 'Stade Rennais FC',
  toulouse: 'Toulouse FC',
  strasbourg: 'RC Strasbourg Alsace',
};

const EPL_OFFICIAL_NAMES: Record<string, string> = {
  arsenal: 'Arsenal FC',
  astonvilla: 'Aston Villa',
  bournemouth: 'AFC Bournemouth',
  brentford: 'FC Brentford',
  brightonandhovealbion: 'Brighton and Hove Albion',
  burnley: 'Burnley FC',
  chelsea: 'Chelsea FC',
  crystalpalace: 'Crystal Palace',
  everton: 'FC Everton',
  fulham: 'FC Fulham',
  leedsunited: 'Leeds United',
  liverpool: 'FC Liverpool',
  manchestercity: 'Manchester City',
  manchesterunited: 'Manchester United',
  newcastleunited: 'Newcastle United',
  nottinghamforest: 'Nottingham Forest',
  sunderland: 'AFC Sunderland',
  tottenhamhotspur: 'Tottenham Hotspur',
  westhamunited: 'West Ham United',
  wolverhamptonwanderers: 'Wolverhampton Wanderers',
};

const SERIEA_OFFICIAL_NAMES: Record<string, string> = {
  atalanta: 'Atalanta BC',
  bologna: 'FC Bologna',
  cagliari: 'Cagliari Calcio',
  como: 'Como 1907',
  cremonese: 'US Cremonese',
  fiorentina: 'ACF Fiorentina',
  genoa: 'Genoa CFC',
  intermilan: 'Inter Milan',
  juventus: 'Juventus Turin',
  lazio: 'SS Lazio',
  lecce: 'US Lecce',
  milan: 'AC Milan',
  napoli: 'SSC Napoli',
  parma: 'Parma Calcio 1913',
  pisa: 'Pisa Sporting Club',
  roma: 'AS Roma',
  sassuolo: 'US Sassuolo',
  torino: 'Torino FC',
  udinese: 'Udinese Calcio',
  verona: 'Hellas Verona',
};

const LALIGA_OFFICIAL_NAMES: Record<string, string> = {
  alaves: 'Alaves',
  almeria: 'Almeria',
  athleticclub: 'Athletic Club',
  atleticomadrid: 'Atletico Madrid',
  barcelona: 'Barcelona',
  cadiz: 'Cadiz',
  celtavigo: 'Celta Vigo',
  getafe: 'Getafe',
  girona: 'Girona',
  granada: 'Granada',
  laspalmas: 'Las Palmas',
  mallorca: 'Mallorca',
  osasuna: 'Osasuna',
  rayovallecano: 'Rayo Vallecano',
  realbetis: 'Real Betis',
  realmadrid: 'Real Madrid',
  realsociedad: 'Real Sociedad',
  sevilla: 'Sevilla',
  valencia: 'Valencia',
  villarreal: 'Villarreal',
};

const BUNDESLIGA_OFFICIAL_NAMES: Record<string, string> = {
  augsburg: 'Augsburg',
  bayerleverkusen: 'Bayer Leverkusen',
  bayernmunich: 'Bayern Munich',
  bochum: 'Bochum',
  borussiadortmund: 'Borussia Dortmund',
  borussiamonchengladbach: 'Borussia Monchengladbach',
  darmstadt98: 'Darmstadt 98',
  eintrachtfrankfurt: 'Eintracht Frankfurt',
  freiburg: 'Freiburg',
  heidenheim: 'Heidenheim',
  hoffenheim: 'Hoffenheim',
  fckoln: 'FC Koln',
  mainz05: 'Mainz 05',
  rbleipzig: 'RB Leipzig',
  unionberlin: 'Union Berlin',
  stuttgart: 'Stuttgart',
  werderbremen: 'Werder Bremen',
  wolfsburg: 'Wolfsburg',
};

const OFFICIAL_TEAM_NAMES: Record<string, string> = {
  ...LIGUE1_OFFICIAL_NAMES,
  ...EPL_OFFICIAL_NAMES,
  ...SERIEA_OFFICIAL_NAMES,
  ...LALIGA_OFFICIAL_NAMES,
  ...BUNDESLIGA_OFFICIAL_NAMES,
};

export function officialTeamName(team: string, normalize: (value: string) => string): string {
  const key = normalize(team);
  return OFFICIAL_TEAM_NAMES[key] ?? team;
}
