export const TEAM_LOGO_MAP: Record<string, string> = {
  //Premier League Teams
  arsenalfc: '/club/Premier_League/Arsenal_FC.png',
  astonvilla: '/club/Premier_League/Aston_Villa_FC.png',
  afcbournemouth: '/club/Premier_League/Bournemouth_AFC.png',
  fcbrentford: '/club/Premier_League/Brentford_FC.png',
  brightonandhovealbion: '/club/Premier_League/Brighton.png',
  burnleyfc: '/club/Premier_League/Burnley.png',
  chelseafc: '/club/Premier_League/Chelsea.png',
  crystalpalace: '/club/Premier_League/Crystal_Palace_FC.png',
  fceverton: '/club/Premier_League/Everton_FC.png',
  fcfulham: '/club/Premier_League/Logo_Fulham.png',
  leedsunited: '/club/Premier_League/Leeds_United_FC.png',
  fcliverpool: '/club/Premier_League/liverpool-fc.png',
  manchestercity: '/club/Premier_League/Manchester_City_FC.png',
  manchesterunited: '/club/Premier_League/Manchester_United_FC.png',
  newcastleunited: '/club/Premier_League/Newcastle_United_FC.png',
  nottinghamforest: '/club/Premier_League/Nottingham_Forest.png',
  afcsunderland: '/club/Premier_League/Sunderland_AFC.png',
  tottenhamhotspur: '/club/Premier_League/Tottenham_Hotspur.png',
  westhamunited: '/club/Premier_League/West_Ham_United_FC.png',
  wolverhamptonwanderers: '/club/Premier_League/Wolverhampton_Wanderer.png',
  
  //Ligue 1 Teams
  
  angerssco: '/club/Ligue_1/Angers_SCO.png',
  ajauxerre: '/club/Ligue_1/AJ_Auxerre.png',
  stadebrestois29: '/club/Ligue_1/Stade_Brestois.png',
  lehavreac: '/club/Ligue_1/Havre_AC.png',
  rclens: '/club/Ligue_1/RC_Lens.png',
  losclille: '/club/Ligue_1/LOSC_Lille.png',
  fclorient: '/club/Ligue_1/FC_Lorient.png',
  lorient: '/club/Ligue_1/FC_Lorient.png',
  olympiquelyonnais: '/club/Ligue_1/Olympique_Lyonnais.png',
  olympiquedemarseille: '/club/Ligue_1/Olympique_de_Marseille.png',
  fcmetz: '/club/Ligue_1/FC_Metz.png',
  asmonacofc: '/club/Ligue_1/AS_Monaco_FC.png',
  asmonaco: '/club/Ligue_1/AS_Monaco_FC.png',
  fcnantes: '/club/Ligue_1/FC_Nantes.png',
  ogcnice: '/club/Ligue_1/OGC_Nice.png',
  parisfc: '/club/Ligue_1/Paris_FC.png',
  parissaintgermain: '/club/Ligue_1/Paris_Saint-Germain.png',
  staderennaisfc: '/club/Ligue_1/Stade_Rennais_FC.png',
  toulousefc: '/club/Ligue_1/Toulouse_FC.png',
  rcstrasbourgalsace: '/club/Ligue_1/Racing_Club_de_Strasbourg_Alsace.png',


  //Serie A Teams
  atalantabc: '/club/Serie_A/Atalanta_Bergamo.png',
  fcbologna: '/club/Serie_A/Bologna_FC.png',
  cagliaricalcio: '/club/Serie_A/cagliari.png',
  como1907: '/club/Serie_A/Como_190.png',
  uscremonese: '/club/Serie_A/US_Cremonese.png',
  acffiorentina: '/club/Serie_A/ACF_Fiorentina.png',
  genoacfc: '/club/Serie_A/Genoa_CFC.png',
  intermilan: '/club/Serie_A/FC_Internazionale_Milano.png',
  juventusturin: '/club/Serie_A/Juventus_FC.png',
  sslazio: '/club/Serie_A/SS_Lazio.png',
  uslecce: '/club/Serie_A/US_Lecce.png',
  acmilan: '/club/Serie_A/AC_Milan.png',
  sscnapoli: '/club/Serie_A/Napoli.png',
  parmacalcio1913: '/club/Serie_A/Parma_Calcio_1913.png',
  pisasportingclub: '/club/Serie_A/Pisa_SC.png',
  asroma: '/club/Serie_A/AS_Roma.png',
  ussassuolo: '/club/Serie_A/sassuolo.png',
  torinofc: '/club/Serie_A/Torino_FC.png',
  udinesecalcio: '/club/Serie_A/Udinese_Calcio.png',
  hellasverona: '/club/Serie_A/Hellas_Verona.png',
};
